"""Vector database for document retrieval using FAISS and sentence transformers."""

import faiss
import numpy as np
import os
import pickle
from sentence_transformers import SentenceTransformer


class VectorDB:
    """Vector database for semantic document search."""
    
    def __init__(self, model_name='all-MiniLM-L6-v2'):
        """Initialize vector database.
        
        Args:
            model_name: Name of the sentence transformer model.
        """
        self.model = SentenceTransformer(model_name)
        self.dim = 384  # Dimension for all-MiniLM-L6-v2
        self.idx = None
        self.docs = []
        
    def _gen_docs(self):
        """Generate synthetic ML/AI documents.
        
        Returns:
            List of synthetic documents.
        """
        return [
            # Week 1 - NLP Fundamentals
            "Natural Language Processing (NLP) is a subfield of artificial intelligence that focuses on enabling computers to understand, interpret, and generate human language. NLP combines computational linguistics with statistical, machine learning, and deep learning models to process text and speech data.",
            
            "Tokenization is the process of breaking down text into smaller units called tokens. These tokens can be words, subwords, or characters. Effective tokenization is crucial for NLP tasks as it forms the foundation for further text processing and analysis.",
            
            "Part-of-speech tagging involves identifying the grammatical parts of speech for each word in a sentence, such as nouns, verbs, adjectives, and adverbs. This helps in understanding the syntactic structure of sentences and is essential for many NLP applications.",
            
            # Week 2 - Deep Learning for NLP
            "Word embeddings are dense vector representations of words that capture semantic relationships. Unlike one-hot encoding, word embeddings place similar words closer together in vector space, enabling models to understand word meanings and relationships.",
            
            "Recurrent Neural Networks (RNNs) are designed to process sequential data by maintaining a hidden state that captures information from previous time steps. This makes them particularly suitable for NLP tasks where word order and context are important.",
            
            "Long Short-Term Memory (LSTM) networks are a type of RNN that addresses the vanishing gradient problem through the use of gates that control the flow of information. LSTMs can maintain long-term dependencies and are widely used in NLP tasks.",
            
            # Week 3 - Transformer Architecture
            "The Transformer architecture revolutionized NLP by replacing recurrent structures with self-attention mechanisms. This allows the model to process all tokens in parallel and capture long-range dependencies more effectively than RNNs.",
            
            "Self-attention is the core mechanism of Transformers that allows each token to attend to all other tokens in the sequence. This enables the model to capture contextual relationships and understand the importance of different words in the context.",
            
            "Multi-head attention extends self-attention by using multiple attention heads in parallel. Each head learns different types of relationships between tokens, allowing the model to capture various aspects of the input simultaneously.",
            
            "Positional encodings are added to token embeddings to provide information about the position of tokens in the sequence. Since Transformers don't have inherent sequential processing, positional encodings help maintain order information.",
            
            # Week 4 - GAN Fundamentals
            "Generative Adversarial Networks (GANs) consist of two neural networks, a generator and a discriminator, that compete against each other in a zero-sum game. The generator tries to create realistic data, while the discriminator tries to distinguish between real and fake data.",
            
            "The generator in a GAN takes random noise as input and produces synthetic data that resembles the training data. Through training, it learns to generate increasingly realistic samples by trying to fool the discriminator.",
            
            "The discriminator in a GAN acts as a binary classifier that distinguishes between real data from the training set and fake data generated by the generator. It provides feedback to the generator through the training process.",
            
            # Week 5 - Advanced GAN Techniques
            "Deep Convolutional GANs (DCGANs) introduced architectural guidelines for stable GAN training, including using convolutional layers instead of fully connected layers, batch normalization, and specific activation functions.",
            
            "Conditional GANs (cGANs) extend the basic GAN framework by providing additional information to both the generator and discriminator. This allows for controlled generation where specific attributes or classes can be specified.",
            
            "StyleGAN introduced a novel architecture that separates high-level and low-level features through style-based modulation. This enables unprecedented control over generated images and has revolutionized high-resolution image synthesis.",
            
            # Week 6 - Applications and Advanced Topics
            "BERT (Bidirectional Encoder Representations from Transformers) is a pre-trained language model that uses bidirectional training to understand context from both directions. It has achieved state-of-the-art results on numerous NLP benchmarks.",
            
            "GPT (Generative Pre-trained Transformer) models are autoregressive language models that generate text sequentially. They have demonstrated remarkable capabilities in text generation, completion, and few-shot learning tasks.",
            
            "Attention mechanisms have become fundamental in modern deep learning, extending beyond NLP to computer vision and other domains. They allow models to focus on relevant parts of the input dynamically, improving interpretability and performance.",
            
            "Transfer learning in NLP involves pre-training models on large text corpora and then fine-tuning them on specific tasks. This approach has significantly reduced the amount of task-specific data required and improved performance across various NLP applications.",
            
            # Additional comprehensive content
            "Natural Language Understanding (NLU) focuses on enabling machines to comprehend human language, including tasks like sentiment analysis, named entity recognition, and relationship extraction. NLU systems must handle ambiguity, context, and linguistic variations.",
            
            "Natural Language Generation (NLG) is the process of producing human-like text from structured data or internal representations. Modern NLG systems use transformer-based models to generate coherent, contextually appropriate responses and content.",
            
            "Sequence-to-sequence models use encoder-decoder architectures to handle tasks where input and output are sequences of different lengths, such as machine translation and text summarization. Attention mechanisms are crucial for aligning input and output sequences.",
            
            "BERT's masked language modeling objective involves randomly masking tokens in the input and training the model to predict them. This bidirectional approach allows BERT to capture deep contextual relationships between words.",
            
            "The Transformer encoder consists of multiple layers of multi-head self-attention and feed-forward networks. Each layer includes residual connections and layer normalization, enabling stable training of deep networks.",
            
            "GAN training instability is a common challenge due to the adversarial nature of the training process. Techniques like gradient penalty, spectral normalization, and alternative loss functions help stabilize training and improve convergence.",
            
            "Variational Autoencoders (VAEs) provide an alternative to GANs for generative modeling by learning a probabilistic latent space. VAEs offer better mode coverage but often produce less sharp samples compared to GANs.",
            
            "Transformer-XL extends the original Transformer architecture by introducing a segment-level recurrence mechanism, enabling the model to handle longer sequences and maintain coherence across document-level contexts.",
            
            "Electra is a pre-training approach that replaces masked language modeling with more efficient replaced token detection. This method trains a discriminator to predict whether each token was replaced, achieving better performance with less computation.",
            
            "ALBERT (A Lite BERT) reduces memory usage and improves training speed through parameter reduction techniques like factorized embedding parameterization and cross-layer parameter sharing while maintaining performance.",
            
            "RoBERTa (Robustly Optimized BERT Pretraining Approach) improves upon BERT through modifications like longer training, larger batches, dynamic masking, and removing next sentence prediction, resulting in better overall performance.",
            
            "T5 (Text-to-Text Transfer Transformer) frames all NLP tasks as text-to-text problems, using a unified approach where both input and output are text sequences. This simplification enables effective multi-task learning and transfer.",
            
            "BART combines bidirectional and autoregressive transformers, using a denoising autoencoder approach. It's particularly effective for text generation tasks and has shown strong performance on summarization and dialogue systems.",
            
            "DeBERTa (Decoding-enhanced BERT) improves upon BERT by disentangling attention from word position and incorporating an enhanced mask decoder, resulting in better performance on various NLP benchmarks.",
            
            "Vision Transformers (ViT) apply transformer architectures to computer vision tasks by treating image patches as tokens. This approach has achieved competitive results with convolutional neural networks while offering different inductive biases.",
            
            "CLIP (Contrastive Language-Image Pre-training) learns visual concepts from natural language supervision, enabling zero-shot image classification and multimodal understanding between text and images.",
            
            "DALL-E and Stable Diffusion represent advances in text-to-image generation, using transformer-based and diffusion-based approaches respectively to create high-quality images from text descriptions.",
            
            "Prompt engineering has become crucial for effectively using large language models, involving careful design of input prompts to elicit desired responses and capabilities from pre-trained models.",
            
            "Few-shot learning enables models to perform tasks with minimal examples by leveraging pre-trained knowledge. This capability has transformed how we approach NLP tasks that traditionally required large labeled datasets.",
            
            "Chain-of-thought prompting encourages models to break down complex problems into step-by-step reasoning, significantly improving performance on arithmetic, logical, and commonsense reasoning tasks.",
            
            "Instruction fine-tuning adapts pre-trained models to follow specific instructions and formats, making them more useful for practical applications and improving their ability to generalize to new tasks.",
            
            "Reinforcement Learning from Human Feedback (RLHF) aligns language models with human preferences through iterative feedback, helping to reduce harmful outputs and improve model behavior on conversational tasks.",
            
            "Scaling laws in deep learning describe how model performance improves with increases in model size, data, and compute. Understanding these relationships guides the development of increasingly capable AI systems.",
            
            "Mixture of Experts (MoE) architectures enable efficient scaling by using sparse activation patterns, where different parts of the network specialize in different types of inputs while maintaining overall model capacity."
        ]
    
    def build_idx(self):
        """Build FAISS index and embed documents."""
        self.docs = self._gen_docs()
        
        embs = self.model.encode(self.docs, show_progress_bar=True)
        
        self.idx = faiss.IndexFlatL2(self.dim)
        self.idx.add(np.array(embs, dtype=np.float32))
        
    def save_idx(self, idx_path="faiss_index.bin", docs_path="documents.pkl"):
        """Save FAISS index and documents.
        
        Args:
            idx_path: Path to save FAISS index.
            docs_path: Path to save documents.
        """
        if self.idx is None:
            self.build_idx()
            
        faiss.write_index(self.idx, idx_path)
        
        with open(docs_path, 'wb') as f:
            pickle.dump(self.docs, f)
        
    def load_idx(self, idx_path="faiss_index.bin", docs_path="documents.pkl"):
        """Load FAISS index and documents.
        
        Args:
            idx_path: Path to FAISS index file.
            docs_path: Path to documents file.
            
        Returns:
            True if loaded successfully, False otherwise.
        """
        if os.path.exists(idx_path) and os.path.exists(docs_path):
            self.idx = faiss.read_index(idx_path)
            with open(docs_path, 'rb') as f:
                self.docs = pickle.load(f)
            return True
        return False
    
    def search(self, query, k=3):
        """Search for relevant documents.
        
        Args:
            query: Search query string.
            k: Number of results to return.
            
        Returns:
            List of search results with document, distance, and index.
        """
        if self.idx is None:
            if not self.load_idx():
                self.build_idx()
                
        q_emb = self.model.encode([query])
        q_emb = np.array(q_emb, dtype=np.float32)
        
        dists, inds = self.idx.search(q_emb, k)
        
        results = []
        for d, idx in zip(dists[0], inds[0]):
            if idx < len(self.docs):
                results.append({
                    'doc': self.docs[idx],
                    'dist': float(d),
                    'idx': int(idx)
                })
                
        return results

def main():
    """Initialize and create the vector database."""
    db = VectorDB()
    db.build_idx()
    db.save_idx()

if __name__ == "__main__":
    main()
